apiVersion: batch/v1
kind: Job
metadata:
   name: init-data
spec:
   template:
      metadata:
         labels:
            app: init-data
      spec:
         containers:
            - name: init-data
              image: nedwebster/bechdel_python_tasks
              imagePullPolicy: Always
              command: ["python", "scripts/init_data.py", "run"]
              env:
              - name: "USERNAME"
                value: "ned.webster"
              - name: "DB_CONNECTION_STRING"
                value: "postgresql://ned_webster:neds_password@postgres:5432/neds_psql_db"
              - name: KAGGLE_USERNAME
                valueFrom:
                  secretKeyRef:
                     name: kaggle-credentials
                     key: KAGGLE_USERNAME
              - name: KAGGLE_KEY
                valueFrom:
                  secretKeyRef:
                     name: kaggle-credentials
                     key: KAGGLE_KEY
         restartPolicy: Never
         imagePullSecrets:
            - name: regcred
   backoffLimit: 4
