services:

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  mlflow-server:
    build: ./services/mlflow_server
    image: mlflow_server
    ports:
      - "5001:5001"
    depends_on:
      - postgres-db

  python-tasks:
    build: 
      context: .
      dockerfile: ./services/python_tasks/Dockerfile
    image: python_tasks
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: "init_data.py run"
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      USERNAME: ${USERNAME}
    depends_on:
      - mlflow-server

  bechdel-flask-app:
    build:
      context: .
      dockerfile: ./services/flask_app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mlflow-server
      - python-tasks

volumes:
  postgres_db:
    driver: local