[tool.poetry]
name = "bechdel-test-predictor"
version = "0.1.0"
description = ""
authors = ["Ned Webster <ned.webster@simplybusiness.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
opendatasets = "^0.1.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
