[tool.poetry]
name = "bechdel-test-predictor"
version = "0.1.0"
description = ""
authors = ["Ned Webster <ned.webster@simplybusiness.co.uk>"]
include = ["src/bechdel_test_predictor/**/*"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
opendatasets = "^0.1.22"
pandas = "^2.1.2"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
