apiVersion: apps/v1
kind: Deployment
metadata:
   name: flask-app
spec:
   replicas: 1
   selector:
      matchLabels:
         app: flask-app
   template:
      metadata:
         labels:
            app: flask-app
      spec:
         containers:
            - name: flask-app
              image: nedwebster/bechdel_flask_app
              imagePullPolicy: IfNotPresent
              env:
              - name: "DB_CONNECTION_STRING"
                value: "postgresql://ned_webster:neds_password@postgres:5432/neds_psql_db"
              ports:
                  - containerPort: 5000